'use client';
import { motion } from 'framer-motion';
import { LineChart, Line, ResponsiveContainer, XAxis, Tooltip } from 'recharts';
import { districts, forecastSeries, nationalKpis, agents } from '@/data/climateData';
import { layers, useClimateStore } from '@/lib/store';
export function CommandCenter(){const {activeLayer,setLayer,selectedDistrict,setDistrict}=useClimateStore(); const district=districts.find(d=>d.district===selectedDistrict)??districts[0]; return <section id="command" className="space-y-6">
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{nationalKpis.map((k,i)=><motion.article initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} transition={{delay:i*.04}} className="glass rounded-3xl p-5" key={k.label}><p className="text-xs uppercase tracking-[.22em] text-cyan">{k.label}</p><div className="mt-3 flex items-end justify-between"><strong className="text-3xl">{k.value}</strong><span className="text-emerald">{k.arrow}</span></div><p className="mt-2 text-sm text-slate-300">{k.trend} · CI {k.confidence}</p></motion.article>)}</div>
 <div className="grid xl:grid-cols-[1.35fr_.65fr] gap-6"><article className="glass rounded-[2rem] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.22em] text-cyan">Digital Twin Map</p><h2 className="text-3xl font-semibold">India operational risk fabric</h2></div><select className="rounded-full bg-cyan text-navy px-4 py-2 font-bold" value={activeLayer} onChange={e=>setLayer(e.target.value as any)}>{layers.map(l=><option key={l}>{l}</option>)}</select></div><div className="mt-5 grid grid-cols-3 md:grid-cols-6 gap-3">{districts.map(d=><button key={d.district} onClick={()=>setDistrict(d.district)} className={`min-h-28 rounded-2xl border p-3 text-left transition hover:-translate-y-1 ${selectedDistrict===d.district?'border-emerald bg-emerald/20':'border-white/10 bg-white/5'}`}><span className="block text-sm font-bold">{d.district}</span><span className="text-xs text-slate-300">{d.state}</span><span className="mt-3 block text-2xl font-black">{activeLayer.includes('Flood')?d.flood:activeLayer.includes('Drought')?d.drought:activeLayer.includes('Heat')?d.heat:activeLayer.includes('AQI')?d.aqi:d.vulnerability}</span></button>)}</div><div className="mt-5 rounded-3xl scan border border-cyan/20 min-h-80 p-6 relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_55%_40%,rgba(76,224,255,.22),transparent_18rem)]"/><p className="relative text-slate-300">Layer stack: district/state boundaries, river basins, watersheds, satellite view, terrain, time slider, and national risk engine.</p><div className="relative mt-8 h-40 rounded-full border border-cyan/40 bg-cyan/5 shadow-glow flex items-center justify-center"><strong className="text-5xl">INDIA</strong><span className="absolute right-10 top-8 h-5 w-5 rounded-full bg-danger animate-pulse"/><span className="absolute left-20 bottom-10 h-4 w-4 rounded-full bg-alert animate-pulse"/></div></div></article>
 <aside className="glass rounded-[2rem] p-6"><p className="text-xs uppercase tracking-[.22em] text-cyan">District Digital Twin</p><h3 className="text-3xl font-semibold">{district.district}</h3><p className="text-slate-300">{district.state} · {district.basin} basin · Population {district.population.toLocaleString('en-IN')}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm">{[['Flood',district.flood],['Drought',district.drought],['Heat',district.heat],['AQI',district.aqi],['Reservoir',district.reservoir],['Vulnerability',district.vulnerability]].map(([a,b])=><div className="rounded-2xl bg-white/5 p-3" key={a}><dt className="text-slate-400">{a}</dt><dd className="text-2xl font-bold">{b}</dd></div>)}</dl><div className="mt-5 rounded-2xl bg-emerald/10 border border-emerald/30 p-4"><b>AI recommendation</b><p className="mt-2 text-sm text-slate-200">{district.recommendation}</p></div></aside></div>
 <div className="grid lg:grid-cols-3 gap-6"><article className="glass rounded-[2rem] p-6 lg:col-span-2"><p className="text-xs uppercase tracking-[.22em] text-cyan">AI Forecasting Center</p><h3 className="text-2xl font-semibold">LSTM · Transformer · GNN · PINN model agreement</h3><div className="h-64"><ResponsiveContainer><LineChart data={forecastSeries}><XAxis dataKey="horizon" stroke="#9fb4cc"/><Tooltip contentStyle={{background:'#06101e',border:'1px solid #28415f'}}/><Line dataKey="rainfall" stroke="#4ce0ff" strokeWidth={3}/><Line dataKey="temp" stroke="#ff9f43" strokeWidth={3}/><Line dataKey="confidence" stroke="#61f2a6" strokeWidth={3}/></LineChart></ResponsiveContainer></div></article><article className="glass rounded-[2rem] p-6"><p className="text-xs uppercase tracking-[.22em] text-cyan">Multi-agent AI</p>{agents.map(a=><div className="mt-3 flex items-center justify-between rounded-2xl bg-white/5 p-3" key={a}><span>{a}</span><span className="text-emerald">online</span></div>)}</article></div></section>}
